settings:
  root_path: /ABSOLUTE/PATH/TO/ALL/YOUR/CODE/PROBLEMS
  codewars_path: EXAMPLE DIRECTORY NAME

ruby:
- name: ruby
  type: directory
  contents:
  - name: src
    type: directory
    contents:
      - name: solution.rb
        type: file
        content_source: code_content
        contents: |
          THIS IS SCRAPED BY DEFAULT
  - name: spec
    type: directory
    contents:
      - name: solution_spec.rb
        type: file
        content_source: test_content
        contents: |
          THIS IS SCRAPED BY DEFAULT
  - name: Rakefile
    type: file
    content_source: user
    contents: |
              # frozen_string_literal: true

              require 'rspec/core/rake_task'
              RSpec::Core::RakeTask.new(:spec)

              desc('Checking for style offenses')
              task(:rubocop) do
                sh 'rubocop --format simple || true'
              end

              task default: %i[rubocop spec]
- name: README.md
  type: file
  content_source: readme
  contents: |
    THIS IS SCRAPED BY DEFAULT
