settings:
  path: "/your/path/to/kata/directory"

files:
  code:
    filename: "solution.rb"
    rel_path: "lib/"
  tests:
    filename: "solution_spec.rb"
    rel_path: "spec/"
  rakefile:
    filename: "Rakefile"
    rel_path: "/"
    content:  |
              # frozen_string_literal: true

              require 'rspec/core/rake_task'
              RSpec::Core::RakeTask.new(:spec)

              desc('Checking for style offenses')
              task(:rubocop) do
                sh 'rubocop --format simple || true'
              end

              task default: %i[rubocop spec]
  desc:
    filename: "README.me"
    rel_path: "/"
