settings:
  path: /code/neyman-e/katare-kid/codewars

files:
  code:
    filename: "1_mine.rb"
    rel_path: "lib/"
    content: |
              def method_name(parameter1, parameter2)

              end
  tests:
    filename: "1_mine_spec.rb"
    rel_path: "spec/"
    content: |
              require "1_mine"

              describe "My solution" do

                it "Should do something" do
                  expect(method_name(argument1, argument2)).to eq(something)
                end

                it "Should do something else" do
                  expect(method_name(argument1, argument2)).to eq(something_else)
                end


                it "Other basic tests" do
                  expect(method_name(argument1, argument2)).to eq(something)
                  expect(method_name(argument1, argument2)).to eq(something)
                  expect(method_name(argument1, argument2)).to eq(something)
                end

              end
  rakefile:
    filename: "Rakefile"
    rel_path: "/"
    content:  |
              require 'rspec/core/rake_task'
              RSpec::Core::RakeTask.new(:spec)

              desc "Look for style guide offenses in your code"
              task :rubocop do
                sh "rubocop --format simple || true"
              end
              task default: [:rubocop, :spec]
  readme:
    filename: "README.me"
    rel_path: "/"
    content:  |
              # Kata's URL


              # Instructions


              # Tests
